config/routes.rb
Rails.application.routes.draw do

  Slug.all.each do |s|
    get "#{s.slug}", to: "#{s.slugable_type.demodulize.pluralize.downcase}#show", as: "custom_#{s.slug.demodulize.pluralize.downcase}", defaults: { id: s.slug }
    post "#{s.slug}", to: "#{s.slugable_type.demodulize.pluralize.downcase}#show", as: "post_custom_#{s.slug.demodulize.pluralize.downcase}", defaults: { id: s.slug }
  end if ActiveRecord::Base.connection.table_exists? :slugs

  resources :news
  resources :posts

  resources :tournaments do
    resources :games
  end
  resources :categories
  resources :teams
  resources :players

  get '/download/:asset_id', to: 'application#file_download', as: :download
  get '/file/:asset_id', to: 'application#file_show', as: :file_show
  # devise_for :users
  mount Ckeditor::Engine => '/ckeditor'
  mount Commontator::Engine => '/commontator'
  mount RailsAdmin::Engine => '/admin', as: :rails_admin
  # resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'
  get '/search(/:searching_params)', to: 'application#search', as: :search
  get '/contact', to: 'application#contact', as: :contact

  devise_for :users, as: :frontend

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end

end

app/views/layouts/partials/_footer.html.haml
%footer#footer.footer-wrap
  .footer-wrap-inner
    .container
      .row
        .col-md-4.col-sm-12.col-xs-12
          .thm-footer-1-inner
            .thm-footer-1
              .footer-logo.pull-left
                .type
                  %div
                    = 'DUFLD'
                  %span.fa.fa-futbol-o
                  %em
                    = '.com.ua'
            = render partial: 'layouts/partials/footer_menu', locals: {menu: @secondary_menu}
            = render partial: 'layouts/partials/footer_menu/social_block'
            .copyright
              %div
                Все права защищены
                != "&reg;"
                %strong dufldo.com.ua
        = @menu_tournaments.each_slice(2) do |categories|
          = render partial: 'layouts/partials/tournaments_footer_menu', collection: categories, as: :category

app/views/layouts/partials/_footer_menu.html.haml
- if menu.present?
  .thm-footer-1
    #nav_menu-2.widget.widget_nav_menu
      .menu-footer-1-container
        %ul#menu-footer-1.menu
          = render partial: 'layouts/partials/footer_menu/footer_static_item', collection: menu, as: :item

app/views/layouts/partials/_header.html.haml
%header#masthead.site-header.header{role: :banner}
  #header-container
    #navigation.container
      .row
        .col-sm-2
          .navbar-header
            %button.navbar-toggle{data: {target: '.navbar-collapse', toggle: :collapse}, type: :button}
              %span.icon-bar
              %span.icon-bar
              %span.icon-bar
            .logo-wrapper
              = link_to root_path, class: %i(navbar-brand) do
                = image_tag 'logo_main.png', class: %i(enter-logo img-responsive)
        .col-sm-10.woo-menu-item-add
          #main-menu.hidden-xs
            %ul#menu-main-menu.nav
              - if @menu_tournaments.present?
                = render partial: 'tournament_categories/tournament_category', collection: @menu_tournaments, as: :category
              - unless current_frontend_user
                %li.signup-signin.menu-item.menu-item-type-post_type.menu-item-object-page.has-menu-child
                  = link_to 'Вход', new_frontend_user_session_path
              - else
                %li.dropdown
                  = link_to '#', class: %i(dropdown-toggle), data: {toggle: :dropdown} do
                    %span.glyphicon.glyphicon-user>
                    %strong
                      = 'Профиль'
                    %span.glyphicon.glyphicon-chevron-down
                  %ul.dropdown-menu
                    %li
                      .navbar-login
                        .row
                          .col-lg-4
                            %p.text-center
                              %span.glyphicon.glyphicon-user.icon-size
                          .col-lg-8
                            %p
                              %strong
                                = current_frontend_user.decorate.full_name
                    %li.divider
                    %li
                      .navbar-login.navbar-login-session
                        .row
                          .col-lg-12
                            %p
                              = link_to 'Выход', destroy_frontend_user_session_path, method: :delete, class: %i(btn btn-warning btn-block)
        #mobile-menu.visible-xs
          .collapse.navbar-collapse
            %ul#menu-main-menu-1.nav.navbar-nav
              - if @menu_tournaments.present?
                = render partial: 'tournament_categories/tournament_category', collection: @menu_tournaments, as: :category
              %li.signup-signin.menu-item.menu-item-type-post_type.menu-item-object-page.has-menu-child
                = link_to 'Вход', new_frontend_user_session_path

app/views/layouts/partials/_secondary_item.html.haml
%li.menu-item.menu-item-type-taxonomy.menu-item-object-league
  = link_to category.name, category.slug_path, title: category.name

app/views/layouts/partials/_secondary_menu.html.haml
#secondary-menu
  .secondary-menu-wrap
    .container
      .row
        .col-md-9
          .secondary-menu
            .navbar
              - if @secondary_menu.present?
                %ul#menu-secondary-menu.nav.navbar-nav.pull-right
                  = render partial: 'layouts/partials/secondary_item', collection: @secondary_menu, as: :category
        .col-md-3.home-search.hidden-xs.hidden-sm
          %form#searchform{action: search_path, method: :get, role: :form}
            %input#s.form-control{autocomplete: :off, name: :searching_params, placeholder: 'Поиск . . . . .', type: :text, value: ''}
            %i.fa.fa-search

app/views/layouts/partials/_tournament_sub_menu.html.haml
- if post.documents.present?
  %li.menu-item.menu-item-type-custom.menu-item-object-custom
    = link_to 'Регламент', post.slug_path(:documents)
- if post.results.present?
  %li.menu-item.menu-item-type-custom.menu-item-object-custom
    = link_to 'Таблица результатов', post.slug_path(:standings)
- if post.teams.present?
  %li.menu-item.menu-item-type-custom.menu-item-object-custom
    = link_to 'Команды', post.slug_path(:teams)
- if post.rounds.present?
  %li.menu-item.menu-item-type-custom.menu-item-object-custom
    = link_to 'Календарь', post.slug_path(:calendar)
%li.menu-item.menu-item-type-custom.menu-item-object-custom
  = link_to 'Комментарии', post.slug_path(:comments_list)

app/views/layouts/partials/_tournaments_footer_menu.html.haml
.col-md-2.col-sm-3.col-xs-4
  .thm-footer-2
    #nav_menu-3.widget.widget_nav_menu
      = link_to category.slug_path do
        %h3.widget_title
          = category.name
      - if category.children.present?
        .menu-footer-2a-container
          %ul#menu-footer-2a.menu
            = render partial: 'layouts/partials/footer_menu/nested_item_menu', collection: category.children.decorate, as: :category