config/routes.rb
Rails.application.routes.draw do

  Slug.all.each do |s|
    get "#{s.slug}", to: "#{s.slugable_type.demodulize.pluralize.downcase}#show", as: "custom_#{s.slug.demodulize.pluralize.downcase}", defaults: { id: s.slug }
    post "#{s.slug}", to: "#{s.slugable_type.demodulize.pluralize.downcase}#show", as: "post_custom_#{s.slug.demodulize.pluralize.downcase}", defaults: { id: s.slug }
  end if ActiveRecord::Base.connection.table_exists? :slugs

  resources :news
  resources :posts

  resources :tournaments do
    resources :games
  end
  resources :categories
  resources :teams
  resources :players

  get '/download/:asset_id', to: 'application#file_download', as: :download
  get '/file/:asset_id', to: 'application#file_show', as: :file_show
  # devise_for :users
  mount Ckeditor::Engine => '/ckeditor'
  mount Commontator::Engine => '/commontator'
  mount RailsAdmin::Engine => '/admin', as: :rails_admin
  # resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'
  get '/search(/:searching_params)', to: 'application#search', as: :search
  get '/contact', to: 'application#contact', as: :contact

  devise_for :users, as: :frontend

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end

end

app/views/tournaments/partials/show/_calendar_item.html.haml
%h3.fixture-title
  = round.formatted_title
= render partial: 'tournaments/partials/show/game_item', collection: round.games.decorate, as: :game

app/views/tournaments/partials/show/_document.html.haml
%tr
  %td
    %i.fa.fa-file-text.ibox-content
    = document.file.original_filename
  %td
    = link_to file_show_path(document.id), class: %i(btn btn-primary), data: {turbolinks: false} do
      = 'Посмотреть'
    = link_to download_path(document.id), class: %i(btn btn-default), data: {turbolinks: false} do
      = 'Скачать'

app/views/tournaments/partials/show/_game_item.html.haml
-#%a{:href => "http://demo.themeum.com/wordpress/wpsoccer/fixture_reasult/barcelona-vs-atletico-madrid/"}
- if game.home_team(true).present? && game.guest_team(true).present?
  .row.fixture-team-inner.clearfix
    = link_to game.home_team.slug_path do
      .col-xs-4.col-sm-4.paddingleft
        = image_tag game.home_team.logo, class: %i(pull-left), alt: game.home_team.name, width: 40
        %h4
          = game.home_team.name
    .col-xs-4.col-sm-4.status.text-center
      = game.get_results
      %span.match-date
        = game.formatted_date
        -#31 Oct 2019 12:00 AM GMT 6+
    = link_to game.guest_team.slug_path do
      .col-xs-4.col-sm-4.text-right
        = image_tag game.guest_team.logo, class: %i(pull-right), alt: game.home_team.name, width: 40
        %h4
          = game.guest_team.name

app/views/tournaments/partials/show/_main_info.html.haml
#fixtures.tab-pane.fade.active.in{role: :tabpanel}
  .container
    .row
      #content.site-content.col-md-12{role: :main}
        %article.status-publish.format-standard.has-post-thumbnail.hentry
          .entry-content-wrap
            .clearfix
            .entry-summary.clearfix
              != tournament.description
              = render partial: 'tournaments/partials/gallery', locals: {gallery: tournament.images}
              = render partial: 'tournaments/partials/gallery_nav', locals: {gallery: tournament.images}

app/views/tournaments/partials/show/_nav_tabs.html.haml
%ul.nav.nav-tabs.match-details-tab-nav{role: :tablist}
  - if tournament.description.present? || tournamnet.images.present?
    %li.active{role: :presentation}
      = link_to 'Основное', '#fixtures', 'aria-controls': :fixtures, 'aria-expanded': false, data: {toggle: :tab}, role: :tab
  - if tournament.documents.present? || tournament.regulations.present?
    %li{role: :presentation}
      = link_to 'Регламент', '#documents', 'aria-controls': :documents, 'aria-expanded': true, data: {toggle: :tab}, role: :tab
  - if tournament.statistics.present?
    %li{role: :statistic}
      = link_to 'Статистика', '#statistic', 'aria-controls': :statistic, 'aria-expanded': :true, data: {toggle: :tab}, role: :tab
  - if tournament.results.present?
    %li{role: :standings}
      = link_to 'Таблица результатов', '#standings', 'aria-controls': :standings, 'aria-expanded': false, data: {toggle: :tab}, role: :tab
  - if tournament.teams.present?
    %li{role: :presentation}
      = link_to 'Команды', '#teams', 'aria-controls': :teams, 'aria-expanded': :true, data: {toggle: :tab}, role: :tab
  - if tournament.rounds.present?
    %li{role: :calendar}
      = link_to 'Календарь', '#calendar', 'aria-controls': :calendar, 'aria-expanded': :true, data: {toggle: :tab}, role: :tab
  %li{role: :comments}
    = link_to 'Комментарии', '#comments_list', 'aria-controls': :comments, 'aria-expanded': :true, data: {toggle: :tab}, role: :tab

app/views/tournaments/partials/show/_regulation.html.haml
%tr
  %td
    %i.fa.fa-file-text.ibox-content
    = regulation.title
  %td
    = button_tag '#', class: %i(btn btn-primary), data: {turbolinks: false, toggle: :modal, target: "#content_#{regulation_counter}"} do
      = 'Посмотреть'
    .modal.fade{role: :dialog, tabindex: -1, id: "content_#{regulation_counter}"}
      .modal-dialog{role: :document}
        .modal-content
          .modal-header
            %button.close{aria: {label: 'Закрыть'}, data: {dismiss: :modal}, type: :button}
              %span{aria: {hidden: true}} ×
            %h4#myModalLabel.modal-title
              = regulation.title
          .modal-body
            != regulation.description
          .modal-footer
            %button.btn.btn-default{data: {dismiss: :modal}, type: :button} Закрыть

app/views/tournaments/partials/show/_team.html.haml
.col-sm-6.paddingleft
  = link_to team.slug_path do
    = image_tag team.logo, alt: team.name, width: 40, class: %i(pull-left)
    %h4
      = team.name

app/views/tournaments/partials/show/_team_position.html.haml
- if result.team_decorate.present?
  %tr
    %td.text-left
      = result.place
    %td.text-left
      = link_to result.team_decorate.slug_path do
        = image_tag result.team_decorate.logo, class: %i(point-table-image), alt: result.team.name
        %span
          = result.team.name
    %td
      = result.count_games
    %td
      = result.count_wins
    %td
      = result.count_draws
    %td
      = result.count_losings
    %td
      = result.goals_balls
    %td
      = result.missed_balls
    %td
      = result.score